### ISSUE TITLE
using an environment variable as the current_version 

### ISSUE THREAD

**Issue by OdedRub** [christian-draeger/bump-semantic-version#15]
Hi,
I'm trying for some time now to make the incremental versioning automatic by passing the previous version to the plugin as the current_version, but it keeps giving the error "previous version '$ENV' is not a semantic version.
I made sure that the value of environment variable (ENV) is actually a valid semantic version (1.0.6) by printing it in different steps.
Is there anything I need to know regarding this issue?

**Comment by christian-draeger** [comment]
Hi which version of the action are you using?

Cheers

**Comment by OdedRub** [comment]
Hey, thanks for your response.
I'm using version 1.1.0 (christian-draeger/increment-semantic-version@1.1.0).
Trying to define something like this-

with
  current-version: ${ENV}
  version-fragment: 'bug'

**Comment by SarahJaine** [comment]
Great action; just wanted to "plus 1" this request to allow the current-version to be an environment variable

**Comment by asheliahut** [comment]
Note to people here if they still care:
`${{ env.VARIABLE_NAME }}` is how you inject those environment variables.
@SarahJaine @OdedRub

**Comment by christian-draeger** [comment]
@asheliahut Thank you for finding out. 
may i kindly ask if you would be so kind to add this to the readme? 🙂
