### ISSUE TITLE
Error: previous version 'v2.50.4-beta' is not a semantic version

### ISSUE THREAD

**Issue by 0xDEnYO** [christian-draeger/bump-semantic-version#22]
Hello @christian-draeger 

we are just recently running into an error `previous version 'v2.50.4-beta' is not a semantic version` even though we didnt change anything in the way tags are produced. 
I've also just updated our git action to use your `v1.2.0` version but that didnt help either. 
Do you have any idea what could be causing this issue?

Here's the link to one of the failing runs: 
https://github.com/lifinance/contracts/actions/runs/12002755792/job/33455204586?pr=871

I tried to re-run failed actions several times but that didnt help either.  

We have the same issue in multiple PRs.

**Comment by christian-draeger** [comment]
Hey Daniel,
sorry for inconvenience.
hope this should be fixed with version 1.2.1

please let me know if you still encounter issues
