### ISSUE TITLE
Is it possible to have a `version-fragment` as `pre`, which is in-between `beta` and `rc`

### ISSUE THREAD

**Issue by egvijayanand** [christian-draeger/bump-semantic-version#7]
Is it possible to have a `version-fragment` defined as `pre`, which is in-between the `beta` and `rc` stages?

The feature has crossed the beta stage but not yet has the potential to be called a release candidate (RC). In this case, this is required to be marked as pre-release.

If not already supported, request to kindly consider adding this as a feature.

**Comment by christian-draeger** [comment]
Not possible right now. but I will add it :)

**Comment by egvijayanand** [comment]
Thank you for taking up this. Appreciate the effort.

**Comment by christian-draeger** [comment]
just released within version 1.1.0
